export const avoidWords: string[] = [
    "whisper",
    "alive",
    "tales",
    "survive",
    "sand", 
    "desert", 
    "opportunity", 
    "heartbeat", 
    "flicker", 
    "hush", 
    "neon lights", 
    "reside", 
    "glance", 
    "echo", 
    "echoes", 
    "stars align", 
    "heart attack", 
    "heart beat", 
    "heart", 
    "we're alive", 
    "thrive", 
    "stride", 
    "break the chains", 
    "chasing dreams", 
    "ignite", 
    "flight", 
    "in this moment", 
    "survive", 
    "hearts unite", 
    "intertwine", 
    "unfold", 
    "untold", 
    "hesitate", 
    "rhyme", 
    "whisper", 
    "whispers", 
    "collide", 
    "collides",
    "shadows",
    "shadow",
    "bold",
    "glow",
    "unseen",
    "keen",
    "spark",
    "sparks",
    "chase",
    "session",
    "confession",
    "electric"
]
